### PR TITLE
Make infobar use the info style color for "All dependancies are satisfied." reference Iss…

### PR DESCRIPTION
**Pull request by SketchNI**
Make infobar blue for "All dependancies are satisfied." reference Issue #4

### CODE REVIEW

**Comment by JosephMcc** [comment]
No issues with this but just some general info. This doesn't actually make the infobar blue. It just adds the info style class to so it will pick up that style as set by your current gtk theme.

**Comment by SketchNI** [comment]
Well, even that's fair enough. Myself and the user who created Issue #4 were in the same mind that it shouldn't be coloured as a warning message as it *is* information.

**Comment by JosephMcc** [comment]
You're correct, it shouldn't be using the warning color in that case. Just wasn't sure if you knew what was happening there since your commit message is a little misleading.

**Comment by SketchNI** [comment]
I'll be honest with you here and say no, I didn't know it was styled depending on the gtk theme but as a happy coincidence, I didn't write any new code to make it blue. Wonder if I can edit a commit message..

**Pull request merged**
